<?php

/**
 * Implements hook_entity_info().
 */
function mod_tarrifs_entity_info()
{
    $return = array(
        'mod_tarrifs' => array(
            'label' => t('Tarrif'),
            'entity class' => 'Tarrifs',
            'controller class' => 'TarrifsController',
            'base table' => 'mod_tarrifs',
            'fieldable' => true,
            'entity keys' => array(
                'id' => 'trfid',
            ),
            'bundles' => array(),
            'uri callback' => 'entity_class_uri',
            'label callback' => 'mod_tarrifs_label',
            'module' => 'mod_tarrifs',
            'admin ui' => array(
                'path' => 'admin/structure/tarrifs',
                'file' => 'mod_tarrifs.admin.inc',
                'controller class' => 'TarrifsUIController',
            ),
            'access callback' => 'mod_tarrifs_access',
        ),
    );

    return $return;
}

/**
 * Implements hook_menu().
 */
function mod_tarrifs_menu()
{
    $items = array();

    /* View */

    $items['tarrifs/%'] = array(
        'title' => 'Tarrif',
        'page callback' => 'mod_tarrifs_view',
        'page arguments' => array('mod_tarrifs', 1),
        'file' => 'mod_tarrifs.pages.inc',
        'access arguments' => array('access mod_tarrifs'),
        'type' => MENU_CALLBACK
    );

    return $items;
}

/**
 * Implements hook_permission().
 */
function mod_tarrifs_permission()
{
    $permissions = array(
        'administer mod_tarrifs' => array(
            'title' => t('Administer mod_tarrifs'),
            'restrict access' => TRUE,
        ),
        'access mod_tarrifs' => array(
            'title' => t('Access to mod_tarrifs'),
            'restrict access' => TRUE,
        )
    );

    return $permissions;
}

/**
 * Access callback
 */
function mod_tarrifs_access($op, $entity, $account = NULL, $entity_type = NULL)
{
    global $user;

    if (!isset($account)) {
        $account = $user;
    }
    switch ($op) {
        case 'create':
        case 'update':
        case 'edit':
        case 'delete':
            return user_access('administer mod_tarrifs', $account);
        case 'view':
            return user_access('access mod_tarrifs', $account);
    }
}

/**
 * Labels
 */

function mod_tarrifs_label($entity, $entity_type) {

    $entity_id = entity_id($entity_type, $entity);

    if (!$entity_id) {
        return '';
    }

    return sprintf('%s - %s - %d', $entity->client, $entity->service, $entity->prefix);
}